### ISSUE TITLE
Can't build with go1.9.2 on Centos 7.2.1511

### ISSUE THREAD

**Issue by applee** [golang/mock#123]
\# runtime
/usr/local/go/src/runtime/mstkbar.go:151:10: debug.gcstackbarrieroff undefined (type struct { allocfreetrace int32; cgocheck int32; efence int32; gccheckmark int32; gcpacertrace int32; gcshrinkstackoff int32; gcrescanstacks int32; gcstoptheworld int32; gctrace int32; invalidptr int32; sbrk int32; scavenge int32; scheddetail int32; schedtrace int32 } has no field or method gcstackbarrieroff)
/usr/local/go/src/runtime/mstkbar.go:162:24: division by zero
/usr/local/go/src/runtime/mstkbar.go:162:43: invalid expression unsafe.Sizeof(composite literal)
/usr/local/go/src/runtime/mstkbar.go:162:44: undefined: stkbar
/usr/local/go/src/runtime/mstkbar.go:212:4: gp.stkbar undefined (type *g has no field or method stkbar)
/usr/local/go/src/runtime/mstkbar.go:213:15: gp.stkbar undefined (type *g has no field or method stkbar)
/usr/local/go/src/runtime/mstkbar.go:216:23: undefined: stackBarrierPC
/usr/local/go/src/runtime/mstkbar.go:226:28: gp.stkbarPos undefined (type *g has no field or method stkbarPos)
/usr/local/go/src/runtime/mstkbar.go:227:19: gp.stkbarPos undefined (type *g has no field or method stkbarPos)
/usr/local/go/src/runtime/mstkbar.go:248:41: undefined: stkbar
/usr/local/go/src/runtime/mstkbar.go:227:19: too many errors

**Comment by balshetzer** [comment]
Hi applee,

I don't see gomock referenced in the error messages. What are you trying to build that generated these errors? Can you show more context?

Thanks,
Hesky

**Comment by balshetzer** [comment]
I'm going to close this for now. Please re-open if you still have this problem and update with more info.

**Comment by applee** [comment]
Sorry for late replay, but there is no more context when  I execute command `go build -v` except above message.

**Comment by balshetzer** [comment]
It looks like you're having this problem:
https://stackoverflow.com/questions/46009258/go-build-fails-runtime-mstkbar-go15110-debug-gcstackbarrieroff-undefined
